services:
    mongo:
        image: mongo
        container_name: realtimechat-mongodb
        privileged: true
        restart: unless-stopped
        env_file:
            - .env.docker
        volumes: 
            - mongodb_data:/data/db
        networks:
            - realtimechat_network
        healthcheck:
            test: mongosh --eval "db.adminCommand('ping')" --quiet
            interval: 10s
            timeout: 10s
            retries: 5

    mongo-express:
        image: mongo-express
        container_name: realtimechat-mongo-express
        restart: unless-stopped
        env_file:
            - .env.docker
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/
            ME_CONFIG_BASICAUTH: true
        depends_on:
            - mongo
        networks:
            - realtimechat_network

    realtimechat-server:
        build:
            context: ./server
            dockerfile: dockerfile
        container_name: realtimechat-server
        restart: unless-stopped
        env_file:
            - .env.docker
        ports:
            - "5000:5000"
        environment:
            - MONGO_URI=${MONGO_URI}?authSource=admin
        depends_on:
            mongo:
                condition: service_healthy
        networks:
            - realtimechat_network
        healthcheck:
            test: "curl -f ${SERVER_URL}:${SERVER_PORT} || exit 1"
            interval: 10s
            timeout: 10s
            retries: 5

    realtimechat-client:
        build:
            context: ./client
            dockerfile: dockerfile
        container_name: realtimechat-client
        restart: unless-stopped
        env_file:
            - .env.docker
        ports:
            - "3000:3000"
        depends_on:
            - realtimechat-server
        networks:
            - realtimechat_network

volumes:
    mongodb_data:

networks:
    realtimechat_network:
        driver: bridge